export const YANGON_TOWNSHIPS = [
  "Ahlone",
  "Bahan",
  "Botataung",
  "Cocokyun",
  "Dagon",
  "Dagon Seikkan",
  "Dala",
  "Dawbon",
  "East Dagon",
  "Hlaing",
  "Hlaingthaya",
  "Hlegu",
  "Hmawbi",
  "Insein",
  "Kamayut",
  "Kawhmu",
  "Kayan",
  "Kungyangon",
  "Kyauktada",
  "Kyeemyindaing",
  "Lanmadaw",
  "Latha",
  "Mayangone",
  "Mingaladon",
  "Mingalar Taungnyunt",
  "North Dagon",
  "North Okkalapa",
  "Pabedan",
  "Pazundaung",
  "Sanchaung",
  "Seikkan",
  "Seikkyi Kanaungto",
  "Shwepyitha",
  "South Dagon",
  "South Okkalapa",
  "Taikkyi",
  "Tamwe",
  "Tantabin",
  "Thaketa",
  "Thanlyin",
  "Thingangyun",
  "Thongwa",
  "Twante",
  "Yankin"
];
